---
title: "SealViewer"
output: html_document
---

Libraries 

Note: Modify the root_dir variable to reflect the location of the directory on your own computer

```{r setup, include=FALSE}
library(tidyverse)
library(shiny)
library(DT)
library(filesstrings)

```



Directories and imagery locations

```{r Directories}

root_dir <- "C:/Users/wmichael/Google Drive/Projects/ShinyViewer"
www_dir <- paste0(root_dir, "/www")
checked_dir <- paste0(root_dir, "/checked")

image.directory <- c(list.files(www_dir,
                                full.names = TRUE))
```


To add: Area Overestimation
        Area underestimation 
        Possible pup


SealViewer application 

```{r SealViewer Application}

#----------------------------#
#          
#           UI 
#
#----------------------------#
ui <- fluidPage(
  titlePanel("Imagery QAQC Tool"),
  
  #----------------------------#
  # Side bar contents
  #----------------------------#
  
  sidebarLayout(
    sidebarPanel(
      
      tags$style(
        HTML(
          ".error {
                    background-color: red;
                    color: white;
                    }
                    .success {
                    background-color: green;
                    color: white;
                    }"
        )),
      
      # Image Selection Section
      h3("Seal Image Quality Check"),
      
      actionButton(inputId = "previous", "Previous"),
      actionButton(inputId = "next", "Next"),
     
      
      
      # Choice Selection Section
      p("Please check the appropriate box below"),
      DT::dataTableOutput('checkbox_table')), 
    
    #----------------------------#
    # Main panel contents
    #----------------------------#
    mainPanel(
      imageOutput(outputId = "myImage")#,
      # textOutput("selected_var")
      ) 
  )
)




#----------------------------#
#          
#           SERVER 
#
#----------------------------#


server <- function(input, output, session) {
  
  # create vector of possible answers
  answer_options <- c("Keep",
                      "Multiple seals in image",
                      "Area understimated",
                      "Area overestimated",
                      "Other error (e.g. ice edge, etc.)")
  
  
  index <- reactiveVal(1)
  
  observeEvent(input[["previous"]], {
    index(max(index()-1, 1))
    
    responses <- data.frame(ImageID = image.directory[index()],
                            Choice = answer_options,
                            Selection = sapply(answer_options, function(i) input[[i]], USE.NAMES = FALSE))
    
    
    
    # if file doesn't exist in current wd, col.names = TRUE + append = FALSE
    # if file does exist in current wd, col.names = FALSE + append = TRUE
    if(!file.exists("SealViewerResponses.csv")) {
      write.table(responses, "SealViewerResponses.csv", 
                  col.names = TRUE, 
                  row.names = FALSE,
                  append = FALSE,
                  sep = ",")
    } else {
      write.table(responses, "SealViewerResponses.csv", 
                  col.names = FALSE, 
                  row.names = FALSE,
                  append = TRUE, 
                  sep = ",")
    }
    # # tell user form was successfully submitted
    # showModal(modalDialog("Successfully submitted",
    #                       easyClose = TRUE,
    #                       footer = NULL,
    #                       class = "success")) 
    
    # # reset all checkboxes and username
    sapply(answer_options, function(x) updateCheckboxInput(session, x, value = FALSE))
    
    
  })
  
  observeEvent(input[["next"]], {
    index(min(index()+1, length(image.directory)))
    
    responses <- data.frame(ImageID = image.directory[index()],
                            Choice = answer_options,
                            Selection = sapply(answer_options, function(i) input[[i]], USE.NAMES = FALSE))
    
    
    
    # if file doesn't exist in current wd, col.names = TRUE + append = FALSE
    # if file does exist in current wd, col.names = FALSE + append = TRUE
    if(!file.exists("SealViewerResponses.csv")) {
      write.table(responses, "SealViewerResponses.csv", 
                  col.names = TRUE, 
                  row.names = FALSE,
                  append = FALSE,
                  sep = ",")
    } else {
      write.table(responses, "SealViewerResponses.csv", 
                  col.names = FALSE, 
                  row.names = FALSE,
                  append = TRUE, 
                  sep = ",")
    }
    # # tell user form was successfully submitted
    # showModal(modalDialog("Successfully submitted",
    #                       easyClose = TRUE,
    #                       footer = NULL,
    #                       class = "success")) 
    
    # # reset all checkboxes and username
    sapply(answer_options, function(x) updateCheckboxInput(session, x, value = FALSE))
    
  })
  
  output$myImage <- renderImage({
    x <- image.directory[index()] 
    list(src = x, alt = "alternate text")
  }, deleteFile = FALSE)
  
  
  
  
  output$selected_var <- renderText(paste("Photo ID:", image.directory[index()]))
  
  
  
  ### 1. create a datatable with checkboxes ###
  # taken from https://github.com/rstudio/DT/issues/93/#issuecomment-111001538
  
  
  # a) function to create inputs
  shinyInput <- function(FUN, ids, ...) {
    inputs <- NULL
    inputs <- sapply(ids, function(x) {
      inputs[x] <- as.character(FUN(inputId = x, label = NULL, ...))
    })
    inputs
  }
  
  # b) create dataframe with the checkboxes
  df <- data.frame(
    Choice = answer_options,
    Selection = shinyInput(checkboxInput, answer_options),
    stringsAsFactors = FALSE
  )
  
  # c) create the datatable
  output$checkbox_table <- DT::renderDataTable(
    df,
    server = FALSE, escape = FALSE, selection = 'none',
    rownames = FALSE,
    options = list(
      dom = 't', paging = FALSE, ordering = FALSE,
      preDrawCallback = JS('function() { Shiny.unbindAll(this.api().table().node()); }'),
      drawCallback = JS('function() { Shiny.bindAll(this.api().table().node()); } ')
    )
  )
}




#----------------------------#
#          
#           APP COMPILER 
#
#----------------------------#

shinyApp(ui = ui, server = server)
```

##short routine to move already checked images from the the "Www" directory to the "checked" directory



```{r Checked Image Updater, echo=FALSE}


# Target and source
root_dir <- "C:/Users/Lynch Lab 7/Desktop/SealViewer"
www_dir <- "C:/Users/Lynch Lab 7/Desktop/SealViewer/www"
checked_dir <- "C:/Users/Lynch Lab 7/Desktop/SealViewer/checked"

# List of all .png files in www directory
all.files  <- list.files(path = root_dir,
                         recursive = TRUE,
                         pattern = ".png",
                         full.names = TRUE)

# List of specific .png files to extract
extract.files <- read.csv(paste0(root_dir, "/SealViewerResponses.csv"), head = TRUE, sep=",")

#Create a list of files that exist in both the SealViewerResponses.csv and the www directory
toCopy <- all.files[which(all.files %in% unlist(extract.files))]

#move the checked images to the checked directory
file.move(toCopy, checked_dir)

```



```{csv cleaner}

csv <- read_csv("SealViewerResponses.csv")
filtered_csv <-  csv %>% 
  filter(Selection == "TRUE")

```



```{string filter}

pattern1 <- image.directory[[1]]

str_view(pattern1, ".png")

pattern2 <- pattern1 %>% 
  str_split("-") 

y[[1]][3] %>% 
  str_split("_")

```